apiVersion: k3d.io/v1alpha5
kind: Simple

subnet: "192.175.243.0/24"

kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  host: "localhost" # important for the `server` setting in the kubeconfig
  hostIP: "127.0.0.1" # where the Kubernetes API will be listening on
  hostPort: "6550" # where the Kubernetes API listening port will be mapped to on your host system

ports:
  - port: 8080:80 # same as `--port '8080:80@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 8081:443 # same as `--port '8081:443@loadbalancer'`
    nodeFilters:
      - loadbalancer
  - port: 22:22 
    nodeFilters:
      - loadbalancer
  - port: 10000-10050:10000-10050
    nodeFilters:
      - loadbalancer
  - port: 10500-10510:10500-10510
    nodeFilters:
      - loadbalancer
options:
  k3d: # k3d runtime settings
    wait: true # wait for cluster to be usable before returining; same as `--wait` (default: true)
    timeout: "300s"