# CSP config file

Listen 80

CSPModulePath "${ISC_PACKAGE_INSTALLDIR}/bin/"
CSPConfigPath "${ISC_PACKAGE_INSTALLDIR}/bin/"

# Serve everything via Web Gateway. Conveniently,
# we needn't worry about sharing this container with non-IRIS applications.
<Location />
    CSP On
</Location>

<Location "/api">
    CSP On
    SetHandler csp-handler-sa
</Location>

<Location /csp>
   CSP On
   SetHandler csp-handler-sa
</Location>

<Location /intersystems/semantic-search/>
  CSP On
  SetHandler csp-handler-sa
  Allow from all
</Location>

<Directory />
    Options MultiViews FollowSymLinks
    AllowOverride None
    Require all granted
    <FilesMatch "\.(log|ini|pid|exe|so)$">
        Require all denied
    </FilesMatch>
</Directory>

# # SSL SECTION #
# # Enable SSL/TLS (https://) on the Apache web server.
# # The user is responsible for providing valid SSL certificates.
# LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
# <VirtualHost *:443>
# SSLEngine on
# SSLCertificateFile "/webgateway-shared/sslwebcert.pem"
# SSLCertificateKeyFile "/webgateway-shared/sslwebkey.pem"
# </VirtualHost>

# Redirect Help links
Redirect /csp/docbook/ http://docs.intersystems.com/irislatest/csp/docbook/