---
version: '3.9'


services:

  business360-iris: 
    image: irepo.intersystems.com/sds-docker-dev/totalview/iris:${VERSION}
    hostname: business360-iris
    cap_add:
      - IPC_LOCK
    security_opt:             
      - seccomp:unconfined
    privileged: true          
    environment:
    - ISC_CPF_MERGE_FILE=/tmp/merge.cpf
    - ISC_DATA_DIRECTORY=/volumes/dur
    - TV_ENCRYPTION_MODE=INSECURE
    command: --key /tmp/iris.key 
    ports:
    - "${CONF_IRIS_LOCAL_WEB_PORT}:52773" 
    - "${CONF_IRIS_LOCAL_JDBC_PORT}:1972" 
    volumes:
    - type: bind
      source: ./licenses/iris.key
      target: /tmp/iris.key
    - type: bind
      source: ./iris-volumes/files-dir
      target: /intersystems/FileInterface
    - type: bind
      source: ./SecurityConfigIRISAuth.json
      target: /etc/config/security/SecurityConfig.json
    - type: bind
      source: ./iris-merge.cpf
      target: /tmp/merge.cpf
    - iris-durable-volume:/volumes           # Using named volumes instead of binds
    networks: 
      - default

  # business360-irisaa:
  #   image: irepo.intersystems.com/sds-docker-dev/totalview/irisaa:${VERSION}
  #   init: true
  #   hostname: business360-irisaa
  #   cap_add:
  #     - IPC_LOCK
  #   security_opt:             # For a demo, this is ok and will provide for more performance. Maybe it is not necessary with privileged:true bellow
  #     - seccomp:unconfined
  #   privileged: true          # For a demo, this is ok and will provide for more performance.
  #   environment: 
  #     ATSCALE_LB_DNS_NAME: "localhost" # Because we will be opening AtScale on our browsers using localhost
  #     DNS_NAME: "business360-irisaa"
  #     IRIS_JDBC_URL: jdbc:IRIS://business360-iris:1972/B360
  #     IRIS_USER: SuperUser
  #     IRIS_PASSWORD: sys
  #     IRIS_CONNECTION_NAME: business360
  #     IRIS_AGGREGATE_SCHEMA: agg
  #   ports:
  #     - "10500-10520:10500-10520"
  #     - 11111:11111
  #   volumes:
  #     - irisaa-data:/opt/atscale/data        # Using named volumes instead of binds 
  #     - irisaa-conf:/opt/atscale/conf        # so that Windows users can start AtScale on their machines
  #     - irisaa-log:/opt/atscale/log
  #     - type: bind                           # These must be normal bind volumes because we need to share
  #       source: ./licenses                   # the license on our machine with AtScale running on the container
  #       target: /etc/atscale-license-secret
  #     - type: bind
  #       source: ./irisaa-volumes/home-atscale
  #       target: /home/atscale

  #   networks: 
  #     - default

  business360-frontend:
    image: irepo.intersystems.com/sds-docker-dev/totalview/frontend:${VERSION}
    hostname: business360-frontend
    security_opt:             
    - seccomp:unconfined
    privileged: true   
    depends_on:
    - business360-iris
    init: true
    ports:
    - "${CONF_FRONTEND_LOCAL_PORT}:80"

    networks: 
      - default


volumes:
  iris-durable-volume:
  irisaa-data:
  irisaa-conf:
  irisaa-log:

networks:
  default:
    ipam:
      config:
        - subnet: ${CONF_DOCKER_SUBNET}
          gateway: ${CONF_DOCKER_GTW}
