#!/bin/bash

export CONF_DOCKER_SUBNET=$(head -1 ./CONF_DOCKER_SUBNET)

export CONF_DOCKER_GTW=$(head -1 ./CONF_DOCKER_GTW)

export CONF_FRONTEND_LOCAL_PORT=$(head -1 ./CONF_FRONTEND_LOCAL_PORT)

export CONF_IRIS_LOCAL_JDBC_PORT=$(head -1 ./CONF_IRIS_LOCAL_JDBC_PORT)

export CONF_IRIS_LOCAL_WEB_PORT=$(head -1 ./CONF_IRIS_LOCAL_WEB_PORT)

export CONF_BASE_WEBGATEWAY_IMAGE_TAG="2026.2"

export CONF_SEMANTIC_SEARCH_LLM_ORCH_IMAGE_TAG="0.13.0.36"

export VERSION=$(head -1 ./VERSION)