---
services:

  business360-iris: 
    image: irepo.intersystems.com/sds-docker-dev/totalview/iris:${VERSION}
    hostname: business360-iris
    cap_add:
      - IPC_LOCK
    security_opt:             
      - seccomp:unconfined
    privileged: true          
    environment:
    - ISC_CPF_MERGE_FILE=/tmp/merge.cpf
    - ISC_DATA_DIRECTORY=/volumes/dur
    - TV_ENCRYPTION_MODE=INSECURE
    command: --key /tmp/iris.key 
    ports:
    - "${CONF_IRIS_LOCAL_JDBC_PORT}:1972" 
    volumes:
    - type: bind
      source: ./licenses/iris.key
      target: /tmp/iris.key
    - type: bind
      source: ./iris-volumes/files-dir
      target: /intersystems/FileInterface
    - type: bind
      source: ./SecurityConfigIRISAuth.json
      target: /etc/config/security/SecurityConfig.json
    - type: bind
      source: ./iris-merge.cpf
      target: /tmp/merge.cpf
    - iris-durable-volume:/volumes           # Using named volumes instead of binds
    networks: 
      - default

  business360-frontend:
    image: irepo.intersystems.com/sds-docker-dev/totalview/frontend:${VERSION}
    hostname: business360-frontend
    security_opt:             
    - seccomp:unconfined
    privileged: true   
    depends_on:
    - business360-iris
    init: true
    ports:
    - "${CONF_FRONTEND_LOCAL_PORT}:80"

    networks: 
      - default

  # This webgateway exists only so people can access the System Management Portal if needed
  # We removed access to the Management Portal from the frontend container
  smp-webgateway:
    image: irepo.intersystems.com/intersystems/webgateway:2024.3
    init: true
    container_name: smp-webgateway
    hostname: smp-webgateway
    environment:
      - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
      - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    volumes:
    - type: bind
      source: ./smp-webgateway-CSP.conf
      target: /webgateway-shared/CSP.conf
    - type: bind
      source: ./smp-webgateway-CSP.ini
      target: /webgateway-shared/CSP.ini
    ports:
    - "${CONF_IRIS_LOCAL_WEB_PORT}:80"

volumes:
  iris-durable-volume:
  irisaa-data:
  irisaa-conf:
  irisaa-log:

networks:
  default:
    ipam:
      config:
        - subnet: ${CONF_DOCKER_SUBNET}
          gateway: ${CONF_DOCKER_GTW}
